// SPDX-License-Identifier: GPL-3.0-or-later
//
// GENERATED by scripts/gen_jalcrpt.py -- do not edit. See that script:
// MAME reads dest[i] = src[L(i ^ addr_xor)] ^ (i & 0xff) ^ data_xor; the
// download stores source byte j at i = Linv(j) ^ addr_xor (bg: bits above
// 19 pass through), XORed with (i & 0xff) ^ data_xor. Inverse and keys
// checked against build_rom_image.decrypt() by the generator.
package ms32_jalcrpt_pkg;
	function automatic logic [18:0] tx_linv(input logic [18:0] j);
		tx_linv[0] = j[11] ^ j[12];
		tx_linv[1] = j[0] ^ j[1];
		tx_linv[2] = j[1] ^ j[2];
		tx_linv[3] = j[14] ^ j[15];
		tx_linv[4] = j[3] ^ j[4];
		tx_linv[5] = j[0];
		tx_linv[6] = j[5] ^ j[6];
		tx_linv[7] = j[15] ^ j[16];
		tx_linv[8] = j[7] ^ j[8];
		tx_linv[9] = j[8] ^ j[9];
		tx_linv[10] = j[10];
		tx_linv[11] = j[10] ^ j[11];
		tx_linv[12] = j[4] ^ j[5];
		tx_linv[13] = j[12] ^ j[13];
		tx_linv[14] = j[13] ^ j[14];
		tx_linv[15] = j[2] ^ j[3];
		tx_linv[16] = j[6] ^ j[7];
		tx_linv[17] = j[16] ^ j[17];
		tx_linv[18] = j[17] ^ j[18];
	endfunction
	function automatic logic [19:0] bg_linv(input logic [19:0] j);
		bg_linv[0] = j[0];
		bg_linv[1] = j[10] ^ j[11];
		bg_linv[2] = j[15] ^ j[16];
		bg_linv[3] = j[7] ^ j[8];
		bg_linv[4] = j[3] ^ j[4];
		bg_linv[5] = j[4] ^ j[5];
		bg_linv[6] = j[5] ^ j[6];
		bg_linv[7] = j[6] ^ j[7];
		bg_linv[8] = j[17] ^ j[18];
		bg_linv[9] = j[8] ^ j[9];
		bg_linv[10] = j[10];
		bg_linv[11] = j[0] ^ j[1];
		bg_linv[12] = j[11] ^ j[12];
		bg_linv[13] = j[12] ^ j[13];
		bg_linv[14] = j[13] ^ j[14];
		bg_linv[15] = j[14] ^ j[15];
		bg_linv[16] = j[1] ^ j[2];
		bg_linv[17] = j[16] ^ j[17];
		bg_linv[18] = j[2] ^ j[3];
		bg_linv[19] = j[18] ^ j[19];
	endfunction
	// per-key (addr_xor, data_xor), indexed by the mod byte's key field:
	//   0 ss91022_10   1 ss92046_01   2 ss92047_01   3 ss92048_01
	localparam logic [18:0] TX_AXOR [0:3] = '{19'h1005d, 19'h1007d, 19'h3405d, 19'h3045d};
	localparam logic [7:0]  TX_DXOR [0:3] = '{8'h35, 8'h7e, 8'h18, 8'hd6};
	localparam logic [19:0] BG_AXOR [0:3] = '{20'hc1c5b, 20'hc1c5a, 20'he5c5b, 20'he185b};
	localparam logic [7:0]  BG_DXOR [0:3] = '{8'ha3, 8'h9b, 8'h55, 8'hd4};
endpackage
