#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Wrap a capture blob into a launcher .mra so the board loads it by itself.

    python scripts/build_capture_mra.py tetrisp-title   -> releases/_dev/Capture tetrisp-title.mra

The blob (scripts/build_capture_blob.py) goes in as <rom index="2"> inline
hex: MiSTer sends every <rom> element of an .mra at launch with its index,
and MS32.sv's loader takes ioctl index 2 as a capture (index 1 is the mod byte). Launching the .mra is
then the whole test -- no OSD file browser, so scripts/mister_hw_test.py can
launch it through MiSTer Remote and screenshot it unattended.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    cap = sys.argv[1]
    variant = sys.argv[2] if len(sys.argv) > 2 else ""          # e.g. "layers" -> capture_layers.bin
    blob = REPO / "debug" / cap / (f"capture_{variant}.bin" if variant else "capture.bin")
    if not blob.exists():
        sys.exit(f"{blob} not found -- run scripts/build_capture_blob.py {cap}")
    data = blob.read_bytes()
    hexlines = "\n".join(data[i:i + 64].hex() for i in range(0, len(data), 64))
    out = REPO / "releases" / "_dev" / f"Capture {cap}{' ' + variant if variant else ''}.mra"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(f"""<!-- Development launcher with the {cap}{' ' + variant if variant else ''} capture blob inline as rom index 2.
     Generated by scripts/build_capture_mra.py; not a game, not part of a release. -->
<misterromdescription>
  <name>Capture {cap}{' ' + variant if variant else ''}</name>
  <setname>MS32</setname>
  <rbf>Arcade-JalecoMS32</rbf>
  <rom index="1"><part>80</part></rom>   <!-- mod byte: bit 7 holds the V70 -->
  <rom index="2">
    <part>
{hexlines}
    </part>
  </rom>
</misterromdescription>
""", encoding="utf-8", newline="\n")
    print(f"{out} ({out.stat().st_size:,} bytes, {len(data):,} of blob)")


if __name__ == "__main__":
    main()
