#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the .mra files: every set in build_rom_image.SETS, laid out to ms32_sdram_top's map.

    python scripts/build_mra.py            -> releases/<Description>.mra
    python scripts/build_mra.py --with-capture tetrisp-title
        -> releases/_dev/<Description> + capture tetrisp-title.mra: the ROMs plus the
           capture blob as rom index 2, so the board renders that frame from the real ROMs

The map is ms32_sdram_top.sv's (this file repeats its bases and sizes and
checks them against that file). Each region is filled by REPEATING its ROM
data to the region size, so tile numbers past the ROM wrap the way MAME's
`% elements` does; the CPU regions are exact. The ymf region is not sent
until Phase 3. Interleaves follow ms32.cpp: ROM_LOAD32_BYTE x4 for the
program (map 0001/0010/0100/1000), ROM_LOAD32_WORD x2 for sprites
(0021/2100). Rom index 1 is the mod byte: [1:0] the decryption key.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
from build_rom_image import SETS, SET_KEY  # noqa: E402

KEY_INDEX = {"ss91022_10": 0, "ss92046_01": 1, "ss92047_01": 2, "ss92048_01": 3}
RBF = "Arcade-JalecoMS32"
NAMES = {"tetrisp": "Tetris Plus (ver 1.0)", "p47aces": "P-47 Aces (ver 1.1)",
         "gametngk": "The Game Paradise - Master of Shooting! (ver 1.0)"}
# region order in the SDRAM map, with the sizes ms32_sdram_top.sv reserves
MAP = [("maincpu", 0x000_0000, 0x200000), ("txtiles", 0x020_0000, 0x080000), ("bgtiles", 0x028_0000, 0x400000),
       ("roztiles", 0x068_0000, 0x400000), ("sprite", 0x0A8_0000, 0x1000000), ("audiocpu", 0x1A8_0000, 0x040000)]


def check_map():
    src = (REPO / "rtl/memory/ms32_sdram_top.sv").read_text(encoding="utf-8")
    for name, base, _ in MAP:
        m = re.search(rf"BASE_{name.upper()}\s*=\s*26'h([0-9A-Fa-f_]+)", src)
        assert m and int(m.group(1).replace("_", ""), 16) == base, (name, base)


def region_xml(region, size, parts):
    """<part>/<interleave> elements for one region as the download stream expects it."""
    kinds = {k for _, _, k in parts}
    if kinds == {"L"}:
        parts_sorted = sorted(parts, key=lambda p: p[1])
        rom_len = sum(1 for _ in parts_sorted)   # not the length; repeat count derived below
        one = "".join(f'      <part name="{fn}"/>\n' for fn, off, _ in parts_sorted)
        return one
    if kinds == {"B"}:
        by_off = sorted(parts, key=lambda p: p[1])
        maps = {0: "0001", 1: "0010", 2: "0100", 3: "1000"}
        return '      <interleave output="32">\n' + "".join(
            f'        <part name="{fn}" map="{maps[off & 3]}"/>\n' for fn, off, _ in by_off) + "      </interleave>\n"
    if kinds == {"W"}:
        # pairs at offsets (4k, 4k+2): each pair one interleave group
        groups = {}
        for fn, off, _ in parts:
            groups.setdefault(off & ~3, []).append((off & 3, fn))
        out = ""
        for base in sorted(groups):
            g = dict(groups[base])
            out += '      <interleave output="32">\n'
            out += f'        <part name="{g[0]}" map="0021"/>\n'
            out += f'        <part name="{g[2]}" map="2100"/>\n'
            out += "      </interleave>\n"
        return out
    raise ValueError(f"{region}: mixed part kinds {kinds}")


def main():
    check_map()
    caps = [a for a in sys.argv[2:]] if len(sys.argv) > 2 and sys.argv[1] == "--with-capture" else []
    out_dir = REPO / "releases" / ("_dev" if caps else "")
    out_dir.mkdir(parents=True, exist_ok=True)
    for game, regions in SETS.items():
        cap = next((c for c in caps if c.split("-")[0] == game), None)
        if caps and not cap:
            continue
        by_name = {r: (size, parts) for r, size, parts in regions}
        xml = [f"<!-- Generated by scripts/build_mra.py from build_rom_image.SETS; the layout is",
               f"     {'DEVELOPMENT: the ROMs plus a capture blob on rom index 2. ' if cap else ''}",
               f"     rtl/memory/ms32_sdram_top.sv's map. Regions are filled by repeating the",
               f"     ROM data to the region size (MAME's tile-number wrap). -->",
               "<misterromdescription>",
               f"  <name>{NAMES.get(game, game)}</name>",
               f"  <setname>{game}</setname>",
               f"  <rbf>{RBF}</rbf>",
               "  <mameversion>0286</mameversion>",
               # DSW at 0xFCC00010, low byte first (MS32.sv sw[0..3]). MAME's defaults for
               # all three sets: every switch off except Language (bit 23) = English, 0.
               f'  <switches default="FF,FF,7F,FF"></switches>']
        # The mod byte always goes first (docs/LESSONS_LEARNED.md): the HPS sends roms in file order.
        key = KEY_INDEX[SET_KEY[game]]
        mod = key | (0x80 if cap else 0)     # bit 7 holds the V70 for capture playback
        xml.append(f'  <rom index="1"><part>{mod:02X}</part></rom>   <!-- mod byte: key {SET_KEY[game]}'
                   f'{", CPU held" if cap else ""} -->')
        xml.append(f'  <rom index="0" zip="{game}.zip" md5="none">')
        pos = 0
        for region, base, rsize in MAP:
            if region not in by_name:
                sys.exit(f"{game}: no {region} region in SETS")
            size, parts = by_name[region]
            if pos != base:
                sys.exit(f"{game}: region {region} would start at {pos:#x}, map says {base:#x}")
            body = region_xml(region, size, parts)
            reps, rem = divmod(rsize, size)
            note = (f", then {rem:#x} bytes of zeros (a partial repeat cannot be expressed; "
                    f"tiles past the ROM read as pen 0 here where MAME wraps)") if rem else ""
            xml.append(f"    <!-- {region}: {size:#x} bytes at {base:#x}, repeated {reps}x{note} -->")
            for _ in range(reps):
                xml.append(body.rstrip("\n"))
            if rem:
                xml.append(f'      <part repeat="{rem:#x}">00</part>')
            pos = base + rsize
        xml.append("  </rom>")
        if cap:
            blob = REPO / "debug" / cap / "capture.bin"
            data = blob.read_bytes()
            xml.append(f'  <rom index="2">   <!-- capture blob {cap}, {len(data)} bytes -->')
            xml.append("    <part>")
            xml.append("\n".join(data[i:i + 64].hex() for i in range(0, len(data), 64)))
            xml.append("    </part>")
            xml.append("  </rom>")
        xml.append("</misterromdescription>")
        text = "\n".join(xml)
        assert text.index('<rom index="1">') < text.index('<rom index="0"'), "mod byte must precede rom index 0"
        path = out_dir / (f"{NAMES.get(game, game)} + capture {cap}.mra" if cap else f"{NAMES.get(game, game)}.mra")
        path.write_text("\n".join(xml) + "\n", encoding="utf-8", newline="\n")
        print(f"{path.name}: {pos:#x} bytes streamed, key {key}")


if __name__ == "__main__":
    main()
