#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate rtl/memory/ms32_jalcrpt_pkg.sv: the tile-ROM decryption for the download path.

    python scripts/gen_jalcrpt.py

MAME (jalcrpt.cpp, transcribed in build_rom_image.py) reads
    dest[i] = src[L(i ^ addr_xor)] ^ (i & 0xff) ^ data_xor
with L a GF(2)-linear cascade of XOR taps. The HPS download delivers the
SOURCE bytes in order j = 0, 1, 2, ..., so the core has to know where each
lands: i = Linv(j) ^ addr_xor (bg keeps the bits above 19 as they are),
and what to store: src ^ (i & 0xff) ^ data_xor. This script inverts L over
GF(2), checks the inverse and then checks the download-order formulation
byte for byte against build_rom_image.decrypt() with every key, and emits
the XOR taps as SystemVerilog functions plus the per-key constants. The
effective address keys are the table entries XORed with the driver's fixed
bases (0x1005d TX, 0xc1c5b BG), exactly as build_rom_image.py applies them.
"""
import random
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
from build_rom_image import TX_TAPS, BG_TAPS, KEYS, decrypt  # noqa: E402

KEY_ORDER = ("ss91022_10", "ss92046_01", "ss92047_01", "ss92048_01")
TX_BASE, BG_BASE = 0x1005d, 0xc1c5b


def matrix(taps, nbits):
    M = [[0] * nbits for _ in range(nbits)]
    for b, c in taps:
        for r in range(nbits):
            M[r][b] = (c >> r) & 1
    return M


def invert(M):
    n = len(M)
    A = [row[:] + [1 if i == r else 0 for i in range(n)] for r, row in enumerate(M)]
    for col in range(n):
        piv = next(r for r in range(col, n) if A[r][col])
        A[col], A[piv] = A[piv], A[col]
        for r in range(n):
            if r != col and A[r][col]:
                A[r] = [x ^ y for x, y in zip(A[r], A[col])]
    return [row[n:] for row in A]


def linv_rows(taps, nbits):
    M = matrix(taps, nbits)
    Mi = invert(M)
    for r in range(nbits):
        for c in range(nbits):
            assert sum(M[r][k] & Mi[k][c] for k in range(nbits)) % 2 == (r == c)
    return [[c for c in range(nbits) if Mi[r][c]] for r in range(nbits)]


def apply_rows(rows, j):
    v = 0
    for r, bits in enumerate(rows):
        b = 0
        for c in bits:
            b ^= (j >> c) & 1
        v |= b << r
    return v


def check(name, taps, nbits, rows, keyidx, top_mask):
    n = (1 << nbits) if name == "TX" else (1 << 21)   # bg: two 1 MB halves, exercising the passthrough bit
    rnd = random.Random(1)
    src = bytes(rnd.getrandbits(8) for _ in range(n))
    mask = (1 << nbits) - 1
    for key in KEY_ORDER:
        k = KEYS[key]
        axor = (k[0] ^ TX_BASE) if name == "TX" else (k[2] ^ BG_BASE)
        dxor = k[1] if name == "TX" else k[3]
        ref = decrypt(src, taps, axor, dxor, top_mask)
        dst = bytearray(n)
        for j in range(n):
            i = (apply_rows(rows, j & mask) ^ axor) | (j & ~mask)
            dst[i] = src[j] ^ (i & 0xff) ^ dxor
        assert bytes(dst) == ref, (name, key)
    print(f"{name}: download-order formulation matches decrypt() for all keys over {n:#x} bytes")


def main():
    tx_rows = linv_rows(TX_TAPS, 19)
    bg_rows = linv_rows(BG_TAPS, 20)
    check("TX", TX_TAPS, 19, tx_rows, 0, 0)
    check("BG", BG_TAPS, 20, bg_rows, 2, ~0xfffff)
    L = ["// SPDX-License-Identifier: GPL-3.0-or-later", "//",
         "// GENERATED by scripts/gen_jalcrpt.py -- do not edit. See that script:",
         "// MAME reads dest[i] = src[L(i ^ addr_xor)] ^ (i & 0xff) ^ data_xor; the",
         "// download stores source byte j at i = Linv(j) ^ addr_xor (bg: bits above",
         "// 19 pass through), XORed with (i & 0xff) ^ data_xor. Inverse and keys",
         "// checked against build_rom_image.decrypt() by the generator.",
         "package ms32_jalcrpt_pkg;"]
    for name, nbits, rows in (("tx", 19, tx_rows), ("bg", 20, bg_rows)):
        L.append(f"	function automatic logic [{nbits-1}:0] {name}_linv(input logic [{nbits-1}:0] j);")
        for r, bits in enumerate(rows):
            L.append(f"		{name}_linv[{r}] = " + (" ^ ".join(f"j[{c}]" for c in bits) if bits else "1'b0") + ";")
        L.append("	endfunction")
    L.append("	// per-key (addr_xor, data_xor), indexed by the mod byte's key field:")
    L.append("	//   0 ss91022_10   1 ss92046_01   2 ss92047_01   3 ss92048_01")
    L.append("	localparam logic [18:0] TX_AXOR [0:3] = '{" + ", ".join(f"19'h{(KEYS[k][0] ^ TX_BASE):05x}" for k in KEY_ORDER) + "};")
    L.append("	localparam logic [7:0]  TX_DXOR [0:3] = '{" + ", ".join(f"8'h{KEYS[k][1]:02x}" for k in KEY_ORDER) + "};")
    L.append("	localparam logic [19:0] BG_AXOR [0:3] = '{" + ", ".join(f"20'h{(KEYS[k][2] ^ BG_BASE):05x}" for k in KEY_ORDER) + "};")
    L.append("	localparam logic [7:0]  BG_DXOR [0:3] = '{" + ", ".join(f"8'h{KEYS[k][3]:02x}" for k in KEY_ORDER) + "};")
    L.append("endpackage")
    out = REPO / "rtl" / "memory" / "ms32_jalcrpt_pkg.sv"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
